name: build x86_64-pc-linux-gnu
on: [push]
jobs:
  x86_64-pc-linux-gnu:
    runs-on: ubuntu-rolling
    steps:
      - run: apt-get update
      - run: apt-get install -y g++ git cmake nodejs zlib1g-dev libssl-dev libkrb5-dev
      - run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
      - run: git clone ${{ github.server_url }}/${{ github.repository }} ${SHORT_SHA}
      - run: cd ${SHORT_SHA} && git checkout ${{ github.sha }}
      - run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=${PWD}/build/debug -DWITH_ZLIB=ON -DWITH_OPENSSL=ON -DBUILD_SAMPLE=OFF -S ${SHORT_SHA} -B build/debug-work && cmake --build build/debug-work --parallel `nproc` && cmake --install build/debug-work
      - run: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=${PWD}/build/release -DWITH_ZLIB=ON -DWITH_OPENSSL=ON -DBUILD_SAMPLE=OFF -S ${SHORT_SHA} -B build/release-work && cmake --build build/release-work --parallel `nproc` && cmake --install build/release-work
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          overwrite: true
          path: |
            build/debug
            build/release
